### ISSUE TITLE
How do you add the checks to Sensu?

### ISSUE THREAD

**Issue by MattHodge** [carllindelof/sensu-checks#1]
Hi this is just a general question. What do your Sensu check .json files look like?

I am doing this:
- On Sensu Server:
  `/etc/sensu/conf.d/somePowerShellCheck.json`

```
{
  "checks": {
    "win32time": {
      "command": "powershell.exe -noprofile -executionpolicy unrestricted -nologo -file C:\\opt\\sensu\\conf.d\\check_windows_services.ps1",
      "subscribers": [
        "production"
      ],
      "interval": 10
    }
  }
}

```
- On Sensu Client:
  Put `check_windows_services.ps1` in `C:\opt\sensu\conf.d\`

Is that the way you would recommend?

**Comment by whyallyn** [comment]
Hey @MattHodge, I just created a pull request that creates a README that should answer your question. Best!
